# Generated by Django 5.1.6 on 2025-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=1000)),
                ("last_name", models.CharField(max_length=1000)),
                ("birth_date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("thriller", "Thriller"),
                    ("comedy", "Comedy"),
                    ("detective", "Detective"),
                    ("fantasy", "Fantasy"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="played_movies", to="core.person"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="directed_movies", to="core.person"
            ),
        ),
    ]
